name: mern-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app-prod

  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - mern-app-prod
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - mern-app-prod
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app-prod
    depends_on:
      - frontend
      - api

volumes:
  mongo-data:
  caddy_data:
  caddy_config:

networks:
  mern-app-prod:
    driver: bridge
