name: mern-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app
  api:
    build:
      context: ./backend
      target: build
    env_file:
      - ./backend/.env
    ports:
      - 4004:4004
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-app
    command: npm run dev
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      target: build
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=https://api.auth.localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    command: npm run dev -- --host
    depends_on:
      - api
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app
    depends_on:
      - frontend
      - api
volumes:
  mongo-data:
  caddy_data:
  caddy_config:
networks:
  mern-app:
    driver: bridge
